{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-{{ .Values.global.serviceAccountName }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ $.Release.Name }}-{{ .Values.global.serviceAccountName }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
  {{- end }}