{
 "title": "EPG Stats",
 "tags": [ "cisco-aci" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "fabric", "label": "Fabric", "query": { "query": "label_values(fabric)" } },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(aci_epg_port_vlan_binding{fabric=\"$fabric\"},tenant)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(aci_epg_port_vlan_binding{fabric=\"$fabric\", tenant=~\"$tenant\"},app)"
    }
   },
   {
    "name": "epg",
    "label": "EPG",
    "query": {
     "query": "label_values(aci_epg_port_vlan_binding{fabric=\"$fabric\", tenant=~\"$tenant\", app=~\"$app\"},epg)"
    }
   },
   { "name": "top", "label": "Tio", "query": "5,10,50" }
  ]
 },
 "panels": [
  {
   "title": "EPG RX Gbits/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk($top,\n    sum by (fabric,tenant,app,epg,nodeid)\n    (\n        rate(aci_epg_rx_unicast_bytes_total{fabric=\"$fabric\",tenant=~\"$tenant\",app=~\"$app\",epg=~\"$epg\"}[$__rate_interval]) +\n        rate(aci_epg_rx_flood_bytes_total{fabric=\"$fabric\",tenant=~\"$tenant\",app=~\"$app\",epg=~\"$epg\"}[$__rate_interval]) + \n        rate(aci_epg_rx_multicast_bytes_total{fabric=\"$fabric\",tenant=~\"$tenant\",app=~\"$app\",epg=~\"$epg\"}[$__rate_interval])\n    )/1.25e+8\n)",
     "legendFormat": "{{tenant}} - {{app}} - {{epg}}"
    }
   ]
  },
  {
   "title": "EPG TX Gbits/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk($top,\n    sum by (fabric,tenant,app,epg,nodeid)\n    (\n        rate(aci_epg_tx_unicast_bytes_total{fabric=~\"$fabric\",tenant=~\"$tenant\",epg=~\"$epg\"}[$__rate_interval]) +\n        rate(aci_epg_tx_flood_bytes_total{fabric=~\"$fabric\",tenant=~\"$tenant\",epg=~\"$epg\"}[$__rate_interval]) + \n        rate(aci_epg_tx_multicast_bytes_total{fabric=~\"$fabric\",tenant=~\"$tenant\",epg=~\"$epg\"}[$__rate_interval])\n    )/1.25e+8\n)",
     "legendFormat": "{{tenant}} - {{app}} - {{epg}}"
    }
   ]
  },
  {
   "title": "RX Drops Pkts/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk($top,\n    sum by (fabric,tenant,app,epg,nodeid)\n    (\n        rate(aci_epg_rx_drop_pkts_total{fabric=~\"$fabric\",tenant=~\"$tenant\",epg=~\"$epg\"}[$__rate_interval])\n    )\n)",
     "legendFormat": "{{tenant}} - {{app}} - {{epg}}"
    }
   ]
  },
  {
   "title": "TX Drops Pkts/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk($top,\n    sum by (fabric,tenant,app,epg,nodeid)\n    (\n        rate(aci_epg_tx_drop_pkts_total{fabric=~\"$fabric\",tenant=~\"$tenant\",epg=~\"$epg\"}[$__rate_interval])\n    )\n)",
     "legendFormat": "{{tenant}} - {{app}} - {{epg}}"
    }
   ]
  }
 ]
}