{
 "title": "Fabric Capacity",
 "tags": [ "cisco-aci" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "fabric", "label": "Fabric", "query": { "query": "label_values(fabric)" } }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aci_nodes{type=\"controller\",fabric=~\"$fabric\"})",
     "legendFormat": "controller"
    },
    {
     "expr": "sum(aci_nodes{type=\"leaf\",fabric=~\"$fabric\"})",
     "legendFormat": "Leaf"
    },
    {
     "expr": "sum(aci_nodes{type=\"spine\",fabric=~\"$fabric\"})",
     "legendFormat": "Spine"
    }
   ]
  },
  {
   "title": "Max Leaves",
   "type": "stat",
   "description": "Max Leaves APIC Capacity",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (fabric) (aci_nodes{type=\"leaf\",fabric=~\"$fabric\"}) / on (fabric) aci_max_capacity{class=\"fabricNode\",nodeid=\"fabric\",fabric=~\"$fabric\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Database Entries",
   "type": "stat",
   "description": "MAC + IP Endpoints (Proxy Database Entries)",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(fabric)(aci_object_instances{fabric=~\"$fabric\",class=~\"fvCEp|fvIp|coopRemoteEp\"})\n/ min by(fabric) (aci_max_proxy_db_capacity{role=\"spine\", fabric=~\"$fabric\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tenants",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_object_instances{class=\"fvTenant\",fabric=~\"$fabric\"}/on(fabric) aci_max_capacity{class=\"fvTenant\",nodeid=\"fabric\",fabric=~\"$fabric\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRFs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_object_instances{class=\"fvCtx\",fabric=~\"$fabric\"}/on(fabric) aci_max_capacity{class=\"fvCtx\",nodeid=\"fabric\",fabric=~\"$fabric\"}",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "BDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_object_instances{class=\"fvBD\",fabric=~\"$fabric\"}/on(fabric) aci_max_capacity{class=\"fvBD\",nodeid=\"fabric\",fabric=~\"$fabric\"}",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "EPGs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_object_instances{class=\"fvAEPg\",fabric=~\"$fabric\"}/on(fabric) aci_max_capacity{class=\"fvAEPg\",nodeid=\"fabric\",fabric=~\"$fabric\"}",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "ESGs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_object_instances{class=\"fvESg\",fabric=~\"$fabric\"}/on(fabric) aci_max_capacity{class=\"fvESg\",nodeid=\"fabric\",fabric=~\"$fabric\"}",
     "legendFormat": "IP Selectior {{fabric}} - {{nodeid}} "
    }
   ]
  },
  {
   "title": "Global PC Tags",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_object_instances{fabric=~\"$fabric\",class=\"fvEPg_Global\"} / on (fabric) aci_max_global_pctag{nodeid=\"fabric\",fabric=~\"$fabric\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L4/L7 Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_object_instances{class=\"vnsCDev\",fabric=~\"$fabric\"}/on(fabric) aci_max_capacity{class=\"vnsCDev\",nodeid=\"fabric\",fabric=~\"$fabric\"}",
     "legendFormat": "IP Selectior {{fabric}} - {{nodeid}} "
    }
   ]
  },
  {
   "title": "L4/L7 Graphs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_object_instances{class=\"vnsGraphInst\",fabric=~\"$fabric\"}/on(fabric) aci_max_capacity{class=\"vnsGraphInst\",nodeid=\"fabric\",fabric=~\"$fabric\"}",
     "legendFormat": "IP Selectior {{fabric}} - {{nodeid}} "
    }
   ]
  }
 ]
}