{
 "title": "Node Detail",
 "tags": [ "cisco-aci" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "fabric", "label": "Fabric", "query": { "query": "label_values(fabric)" } },
   {
    "name": "nodeid",
    "label": "Nodeid",
    "query": {
     "query": "query_result(aci_uptime_seconds_total{fabric=~\"$fabric\",role!=\"controller\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aci_node_cpu_user_ratio{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}  + aci_node_cpu_kernel_ratio{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "Node memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aci_node_memory_used_bytes{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} / aci_node_memory_total_bytes{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "Node health ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aci_health_ratio{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  }
 ]
}