{
 "title": "Nodes Interfaces",
 "tags": [ "cisco-aci" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fabric",
    "label": "Fabric",
    "query": {
     "query": "label_values(aci_uptime_seconds_total,fabric)"
    }
   },
   {
    "name": "nodeid",
    "label": "Nodeid",
    "query": {
     "query": "label_values(aci_uptime_seconds_total{fabric=\"$fabric\", role!=\"controller\"},nodeid)"
    }
   },
   { "name": "top", "label": "Tio", "query": "5,10,50" }
  ]
 },
 "panels": [
  {
   "title": "Interface Status",
   "type": "stat",
   "description": "Limited to 50 interfaces",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(50, aci_interface_oper_state{fabric=~\"$fabric\", nodeid=~\"$nodeid\"} == 2)",
     "legendFormat": "{{nodeid}} {{interface}}"
    },
    {
     "expr": "topk(50, aci_interface_oper_state{fabric=~\"$fabric\", nodeid=~\"$nodeid\"} == 1)",
     "legendFormat": "{{nodeid}} {{interface}}"
    }
   ]
  },
  {
   "title": "Interface RX Usage %",
   "type": "timeseries",
   "description": "Top 10 Used interfaces",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk($top,\n  ( rate(aci_interface_rx_unicast_bytes_total{interface_type=\"phys\",fabric=~\"$fabric\",nodeid=~\"$nodeid\"}[$__rate_interval]) + \n    rate(aci_interface_rx_broadcast_bytes_total{interface_type=\"phys\",fabric=~\"$fabric\",nodeid=~\"$nodeid\"}[$__rate_interval]) + \n    rate(aci_interface_rx_multicast_bytes_total{interface_type=\"phys\",fabric=~\"$fabric\",nodeid=~\"$nodeid\"}[$__rate_interval])\n  ) / on (fabric,nodeid, interface) group_left aci_interface_oper_speed_bps{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} * 800 \n)",
     "legendFormat": "{{fabric}} - {{nodeid}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Interface TX Usage %",
   "type": "timeseries",
   "description": "Top 10 Used interfaces",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "topk($top,\n  ( rate(aci_interface_tx_unicast_bytes_total{interface_type=\"phys\",fabric=~\"$fabric\",nodeid=~\"$nodeid\"}[$__rate_interval]) + \n    rate(aci_interface_tx_broadcast_bytes_total{interface_type=\"phys\",fabric=~\"$fabric\",nodeid=~\"$nodeid\"}[$__rate_interval]) + \n    rate(aci_interface_tx_multicast_bytes_total{interface_type=\"phys\",fabric=~\"$fabric\",nodeid=~\"$nodeid\"}[$__rate_interval])\n  ) / on (fabric,nodeid, interface) group_left aci_interface_oper_speed_bps{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} * 800\n)",
     "legendFormat": "{{fabric}} - {{nodeid}} - {{interface}}"
    }
   ]
  }
 ]
}